@startuml
class org.lia.java_lab8_client_v2.multithreading.SendRequest {
~ GetRequest request
+ void run()
}


interface org.lia.java_lab8_client_v2.commands.Command {
~ Response execute()
~ void setCollectionManager(CollectionManager)
~ void setSqlManager(SqlManager)
~ void setCommandManager(CommandManager)
~ String description()
+ String getLogin()
+ String getPassword()
}

class org.lia.java_lab8_client_v2.models.Coordinates {
- {static} long serialVersionUID
- long x
- double y
+ long getX()
+ double getY()
+ void setX(long)
+ void setY(double)
+ boolean equals(Object)
+ int hashCode()
+ String toString()
}


class org.lia.java_lab8_client_v2.commands.MinByIdCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.managers.SqlManager {
~ String username
~ String password
~ String url
~ Connection connection
+ CollectionManager getCollectionFromDatabase()
+ long addElement(Product)
+ void updateElement(Product)
+ long addUser(String,String)
+ long checkUser(String,String)
+ void deleteElementsByUserId(long)
+ int deleteElementById(long,long)
}


class org.lia.java_lab8_client_v2.commands.ShowCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.models.Organization {
- {static} long serialVersionUID
- Long id
- String name
- String fullName
- Integer employeesCount
- {static} Long currentId
+ Long getId()
+ void setId(Long)
+ String getName()
+ void setName(String)
+ String getFullName()
+ void setFullName(String)
+ Integer getEmployeesCount()
+ void setEmployeesCount(Integer)
+ {static} void updateId(long)
+ boolean equals(Object)
+ int hashCode()
+ String toString()
+ int compareTo(Organization)
}


class org.lia.java_lab8_client_v2.models.Product {
- {static} long serialVersionUID
- long id
- String name
- Coordinates coordinates
- java.sql.Date creationDate
- Integer price
- String partNumber
- Integer manufactureCost
- UnitOfMeasure unitOfMeasure
- Organization manufacturer
- long userId
+ void setup()
+ void setId(long)
+ long getId()
+ String getName()
+ void setName(String)
+ Coordinates getCoordinates()
+ void setCoordinates(Coordinates)
+ Date getCreationDate()
+ void setCreationDate(Date)
+ Integer getPrice()
+ void setPrice(Integer)
+ String getPartNumber()
+ void setPartNumber(String)
+ Integer getManufactureCost()
+ void setManufactureCost(Integer)
+ UnitOfMeasure getUnitOfMeasure()
+ void setUnitOfMeasure(UnitOfMeasure)
+ Organization getManufacturer()
+ void setManufacturer(Organization)
+ void setUserId(long)
+ long getUserId()
+ boolean equals(Object)
+ int hashCode()
+ String toString()
+ int compareTo(Product)
}


class org.lia.java_lab8_client_v2.multithreading.GetRequest {
~ ByteBuffer buf
~ DatagramChannel dc
~ CollectionManager collectionManager
~ SqlManager sqlManager
~ CommandManager commandManager
~ Command command
~ Response response
~ WorkRequest working
~ SendRequest answer
~ SocketAddress address
~ ExecutorService executor
+ void run()
}


class org.lia.java_lab8_client_v2.commands.AddCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- Product product
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.ClearCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.UpdateCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- Product product
- String login
- String password
~ long productId
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.tools.Response {
- {static} long serialVersionUID
- Product product
- ArrayList<String> answer
- ArrayDeque<Product> productCollectionResponse
- boolean success
- long userId
- long countObjects
+ Product getProduct()
+ void setProduct(Product)
+ ArrayList<String> getAnswer()
+ void addAnswer(String)
+ void setProductCollectionResponse(ArrayDeque<Product>)
+ ArrayDeque<Product> getProductCollectionResponse()
+ void setSuccess(boolean)
+ boolean getSuccess()
+ void setUserId(long)
+ long getUserId()
+ long getCountObjects()
+ void setCountObjects(long)
}


class org.lia.java_lab8_client_v2.commands.RemoveLowerCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- long id
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.PrintFieldAscendingManufacturerCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


enum org.lia.java_lab8_client_v2.models.UnitOfMeasure {
+  CENTIMETERS
+  SQUARE_METERS
+  MILLILITERS
+  GRAMS
}

class org.lia.java_lab8_client_v2.managers.CommandManager {
- Map<String,Command> commandsManager
- CollectionManager collectionManager
- SqlManager sqlManager
~ DatagramChannel dc
~ ByteBuffer buf
~ InetAddress host
~ int port
~ SocketAddress addr
+ void listen()
+ void getInputFromConsole()
+ Map<String,Command> getCommandsList()
+ CollectionManager getCollectionManager()
}


class org.lia.java_lab8_client_v2.managers.CollectionManager {
- ArrayDeque<Product> productCollection
- java.time.LocalDate creationDate
+ ArrayDeque<Product> getProductCollection()
+ long getNumberOfElements()
+ void setProductCollection(ArrayDeque<Product>)
+ void addToCollection(Product)
+ void removeFromCollection(Product)
+ void changeIdIndex()
+ Product getById(long)
+ String shortInfo()
+ void show()
+ String toString()
}


class org.lia.java_lab8_client_v2.managers.FileManager {
- String filename
- XStream xstream
+ String getFilename()
+ boolean checkFileExists()
+ void writeCollection(ArrayDeque<Product>)
+ CollectionManager readCollection()
}


class org.lia.java_lab8_client_v2.multithreading.WorkRequest {
~ GetRequest request
+ void run()
}


class org.lia.java_lab8_client_v2.Main {
+ {static} void main(String[])
}

class org.lia.java_lab8_client_v2.commands.AddIfMaxCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- Product product
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.GetByIdCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- long id
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.RemoveHeadCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.CountByPartNumberCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String partNumber
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.SignUpCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- String login
- String passwordString
- byte[] passwordByte
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.RemoveByIdCommand {
- {static} long serialVersionUID
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
- long id
- String login
- String password
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.LoginCommand {
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
+ Product product
- String login
- String passwordString
- byte[] passwordByte
- String password
- {static} long serialVersionUID
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}


class org.lia.java_lab8_client_v2.commands.InfoCommand {
- {static} long serialVersionUID
- String login
- String password
- CollectionManager collectionManager
- SqlManager sqlManager
- CommandManager commandManager
+ String description()
+ Response execute()
+ void setCollectionManager(CollectionManager)
+ void setSqlManager(SqlManager)
+ void setCommandManager(CommandManager)
+ String getLogin()
+ String getPassword()
}




org.lia.java_lab8_client_v2.multithreading.Runnable <|.. org.lia.java_lab8_client_v2.multithreading.SendRequest
java.io.Serializable <|-- org.lia.java_lab8_client_v2.commands.Command
java.io.Serializable <|.. org.lia.java_lab8_client_v2.models.Coordinates
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.MinByIdCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.ShowCommand
org.lia.java_lab8_client_v2.models.Comparable <|.. org.lia.java_lab8_client_v2.models.Organization
java.io.Serializable <|.. org.lia.java_lab8_client_v2.models.Organization
org.lia.java_lab8_client_v2.models.Comparable <|.. org.lia.java_lab8_client_v2.models.Product
java.io.Serializable <|.. org.lia.java_lab8_client_v2.models.Product
org.lia.java_lab8_client_v2.multithreading.Runnable <|.. org.lia.java_lab8_client_v2.multithreading.GetRequest
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.AddCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.ClearCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.UpdateCommand
java.io.Serializable <|.. org.lia.java_lab8_client_v2.tools.Response
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.RemoveLowerCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.PrintFieldAscendingManufacturerCommand
org.lia.java_lab8_client_v2.multithreading.Runnable <|.. org.lia.java_lab8_client_v2.multithreading.WorkRequest
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.AddIfMaxCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.GetByIdCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.RemoveHeadCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.CountByPartNumberCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.SignUpCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.RemoveByIdCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.LoginCommand
org.lia.java_lab8_client_v2.commands.Command <|.. org.lia.java_lab8_client_v2.commands.InfoCommand
@enduml